### ISSUE TITLE
Enhance the usability of the edition of Audit parameters

### ISSUE THREAD

**Issue by phacks** [theodo/falco#30]
Here are a few suggestions to enhance the edition of audit parameters:

- [ ] When I add an audit parameter, if I click on the configuration select list, I should not exit the edition mode;
- [ ] When I add an audit parameter, if I hit <kbd>Enter</kbd> my input is submitted
- [ ] When I add an audit parameter, the new line in the table is aligned with existing ones (see screenshot).

![image](https://user-images.githubusercontent.com/2587348/67210693-d23bb980-f419-11e9-9436-1bda41b8881e.png)

@alexfauquette would you be willing to work on this? @LouisPinsard can help you navigate this corner of the codebase :)

**Comment by alexfauquette** [comment]
Ok, sounds interesting :)

**Comment by alexfauquette** [comment]
**current rules**

When an input is losing focus, if the row is completed, data are saved. If there is no data at all, the row is closed. That's why clicking to select configuration exit edit mode (name input lose focus without any data).

To simplify all that, I propose to add 2 buttons on the right. One to validate data and the other one to close edition mode.

![Capture d’écran de 2019-10-21 17-54-35](https://user-images.githubusercontent.com/45398769/67221653-1c2d9b00-f42c-11e9-8ade-c6e389927180.png)

**Comment by phacks** [comment]
@alexfauquette Interesting!

In that proposition, what would happen if we click outside the row without validating it?
